apiVersion: v2
dependencies:
- condition: alertmanager.enabled
  name: alertmanager
  repository: file://./charts/alertmanager
- name: common
  repository: file://./charts/common
- condition: knowledge-sensor.enabled
  name: knowledge-sensor
  repository: file://./charts/knowledge-sensor
- alias: postgres
  condition: postgres.enabled
  name: postgresql
  repository: file://./charts/postgresql
- alias: promxyuser
  condition: promxyuser.enabled
  name: promxy
  repository: file://./charts/promxy
- alias: redisearch
  condition: redisearch.enabled
  name: redis
  repository: file://./charts/redis
- alias: tsdb
  condition: tsdb.enabled
  name: victoria-metrics-single
  repository: file://./charts/victoria-metrics-single
description: Asserts Helm Chart to configure entire asserts stack
icon: https://www.asserts.ai/favicon.png
maintainers:
- name: Asserts
  url: https://github.com/asserts
name: asserts
type: application
version: 1.3.0
kubeVersion: ">= 1.17"
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: asserts
  catalog.cattle.io/display-name: Asserts - Get to the root cause faster